apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-app.fullname" . }}
  labels:
    app: {{ include "platform-app.name" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "platform-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http