replicaCount: 2

image:
  repository: ghcr.io/manubarrionuevo/platform-app
  tag: "c6a56b3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

serviceMonitor:
  enabled: false
  interval: 15s

app:
  env: dev